spring:
  cloud:
    config:
      name: "cards"
      profile: "prod"
  config:
    import: "optional:configserver:http://team6-config-server:8762/"


eureka:
  client:
    serviceUrl:
      defaultZone: http://team6-eureka-server:8761/eureka/